### ISSUE TITLE
Only option present is 'Note Copy', no option for setting the card to new

### ISSUE THREAD

**Issue by longbk123** [Arthur-Milchior/anki-copy-note#10]
![image](https://user-images.githubusercontent.com/17146873/72002852-3b132080-3216-11ea-9f9e-1d2e39c98b93.png)

**Comment by longbk123** [comment]
Version 2.1.15 (442df9d6)
Qt 5.12.1 PyQt 5.11.3

**Comment by Arthur-Milchior** [comment]
You need to change th option in the add-on config.
