### ISSUE TITLE
The add-on doesn't work with the most recent version of Anki (2.1.26)

### ISSUE THREAD

**Issue by pinnerup** [Arthur-Milchior/anki-copy-note#14]
Thanks for a great add-on!

Upgrading to Anki 2.1.26, I'm sad to see that it is deemed incompatible.

I hope you will update the add-on so that it'll work again.

Best regards,
Rasmus

**Comment by Arthur-Milchior** [comment]
I posted a bug report to anki. It is supposed to work with current version, and I don't know why it tells you it is not compatible

https://anki.tenderapp.com/discussions/ankiweb/4795-not-able-to-change-version/autosuggest

**Comment by pinnerup** [comment]
Thanks. Apparently Anki accepts the extension now, but when using it, I get an error message. I've written the details here: 

https://anki.tenderapp.com/discussions/add-ons/44743-error-in-copy-notes-add-on

**Comment by pinnerup** [comment]
The extension now works with no error messages again :)

**Comment by Arthur-Milchior** [comment]
I honestly have no idea what went wrong. Sorry for the time lost
