### ISSUE TITLE
Due date is not reset

### ISSUE THREAD

**Issue by aleksejrs** [Arthur-Milchior/anki-copy-note#17]
I fail a card; Rememorize reschedules its siblings; I copy the note as new… one of the cards (probably the one I failed, hence the one that was Relearning) is due today — "is:new is:due". 

Anki 2.1.22, config.json:

```json
{
  "Shortcut: copy":"Ctrl+C",
  "Preserve creation time" : false,
  "Preserve ease, due, interval...": false,
  "Copy log": false,
  "correct import": true,
  "current tag prefix": "relation-",
  "tag prefixes": ["relation-", "relation_"],
  "relate copies": false
}
```

**Comment by Arthur-Milchior** [comment]
What is "Rememorize" ? 
I'm really sorry I absolutly don't get what you are saying. Can you maybe write more sentences and smaller sentences ? A list of actions to create the bug

**Comment by aleksejrs** [comment]
Sorry, it's [ReMemorize: Rescheduler with sibling and logging (v1.4.0)](https://ankiweb.net/shared/info/323586997). Source code: https://github.com/lovac42/ReMemorize

I think Copy Note simply fails to remove the Due date from Relearning cards. It goes something like this:

1. Install ReMemorize
2. Make sure its "reschedule_siblings_on_again": true.
3. Fail a card whose sibling, I guess, must have an Interval over "sibling_boundary". The sibling will be rescheduled, the card will be new.
4. Copy the note with this add-on, without saving history and other numbers.

The note has no history, no intervals, but only the failed card still has a Due date. The Due date is hopefully safely removed simply by rescheduling the card as new.

**Comment by aleksejrs** [comment]
I am switching to newer Anki, and everything is so different I'll just close this.

**Comment by aleksejrs** [comment]
I am switching to a newer Anki, and everything is so different I'll just close this.
