### ISSUE TITLE
"Invalid configuration" error when trying to save options

### ISSUE THREAD

**Issue by elias6** [Arthur-Milchior/anki-copy-note#22]
I am using Anki 2.1.35 on macOS 10.15.6 (Catalina) and I just downloaded Anki Copy Note.

I want to copy some cards from a deck, and I don't care about copying the history (creation time, ease, etc), so I went to "Tools", then "Add-ons", then "Copy notes", then "Config". I changed the "Copy log", "Preserve creation time", and "Preserve ease, due, interval..." settings to false, clicked "OK", and saw a dialog box saying `Invalid configuration: TypeError("argument of type 'NoneType' is not iterable")` with a single button saying "OK".

I thought I messed something up in the config, so I clicked "Restore Defaults", then "OK", and saw the same error.

How can I be able to save my preferences for Copy Note?

**Comment by Arthur-Milchior** [comment]
I can't currently reproduce, at least not with default. Can you reproduce it or is it gone?

**Comment by elias6** [comment]
Hmm... I was able to reproduce it today. But then Anki told me there was an update for this add-on, and I restarted Anki, and now it is working. So I guess it is fixed.

**Comment by Arthur-Milchior** [comment]
I was fixing other issues indeed. No dea why this was was fixed too
