### ISSUE TITLE
The creation time is not preserved in the copied card when "Preserve creation time" is set to true.

### ISSUE THREAD

**Issue by ventoteso** [Arthur-Milchior/anki-copy-note#28]
I use anki version 2.1.44.
The "Preserve creation time" is set to true. However the date of creation of the new card (the copy) is the date when the copy was made, not the date of creation of the original card, which is the expected behaviour.

Config:
{
    "Copy log": true,
    "Preserve creation time": true,
    "Preserve ease, due, interval...": true,
    "Shortcut: copy": "Ctrl+C",
    "correct import": true,
    "current tag prefix": "relation_",
    "relate copies": false,
    "tag for copies": "Copy",
    "tag prefixes": [
        "relation_"
    ]
}

**Comment by Arthur-Milchior** [comment]
Can you please update the add-on and check. I think I corrected it.
Thanks for the bug report

**Comment by ventoteso** [comment]
Corrected.
Thank you.
