### ISSUE TITLE
Anki freezes when trying to copy more than 3 cards

### ISSUE THREAD

**Issue by wildpyre009** [Arthur-Milchior/anki-copy-note#4]
Hello,

 I am using the copy notes addon: https://ankiweb.net/shared/info/1566928056

    It was working fine until the last few days. Now anytime I try to copy notes more than 3 the whole program freezes and I have to restart anki. This happens on my windows and mac version. If i copy 2 cards, anki doesnt freeze but it takes several minutes for the program to process copying cards. Thanks for your help!

**Comment by Arthur-Milchior** [comment]
I can't reproduce this. Can you please let me know what is your current configuration. (From add-on manager, select «copy note», click on «config»). 

Can you also please let me know what other add-on you have. A screen shot would be sufficient. It may helps figure out whether another add-on is interacting.

**Comment by wildpyre009** [comment]
Hi,

I've attached my current addons and configuration. As for the specific notes, the problem occurs with every note I try. I have the zanki/lightyear medical boards study decks that I try to copy from and it has the freezing problem. I made a video highlighting the problem that you can view here  https://youtu.be/059O45T1Ofw

![configuration](https://user-images.githubusercontent.com/55603485/65873983-964d9100-e352-11e9-8e7a-6aad8cf3c324.PNG)

**Comment by Arthur-Milchior** [comment]
The video is private. I can't see it though the link you give me. Please, can you make your video «protected» instead. So it won't be referenced but I can see it.

**Comment by Arthur-Milchior** [comment]
This seems to be a duplicate of #5

**Comment by wildpyre009** [comment]
Hello I've made the video public. Let me know if youre still having trouble with viewing it!

**Comment by Arthur-Milchior** [comment]
It should be corrected now.

**Comment by wildpyre009** [comment]
That worked. Thank you so much!!
